apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        autoscaling.alpha.kubernetes.io/scan: 'true'
        autoscaling.alpha.kubernetes.io/conditions: 'cpu > 50'
    spec:
      containers:
        - name: client
          image: ashwathama14/ticketing-client
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: client-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-depl
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
