apiVersion: v1
kind: PersistentVolume
metadata:
  name: tickets-mongo-pv2
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/tickets-mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tickets-mongo-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  storageClassName: ''
  volumeName: tickets-mongo-pv2

---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  selector:
    app: tickets-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
        - name: tickets-mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: tickets-mongo-persistent-storage2
              mountPath: /data/db
          resources:
            limits:
              memory: 512Mi
              cpu: 0.5
            requests:
              memory: 256Mi
              cpu: 0.25
      volumes:
        - name: tickets-mongo-persistent-storage2
          persistentVolumeClaim:
            claimName: tickets-mongo-pvc2
